name: Python application

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        echo "${{ secrets.DOCKERPW }}" | docker login -u "SkandaSBhat" --password-stdin
        docker image build -t SkandaSBhat/hello-python .
        docker push SkandaSBhat/hello-python
